# Double-Take-Go-Reborn Configuration for CPU-based OpenCV integration
# Diese Konfiguration ist optimiert für die Standard-CPU-Nutzung von OpenCV
# HINWEIS: OpenCV kann unabhängig von CompreFace verwendet werden

log:
  level: "info"
  format: "text"
  timestamp: true

server:
  port: 3000
  host: "0.0.0.0"
  base_url: "http://localhost:3000"
  metrics_enabled: true

mqtt:
  enabled: true
  broker: "192.168.0.55"
  port: 1883
  username: "hans"
  password: "desert"
  client_id: "double-take-go"
  topic_prefix: "double-take"
  topic: "frigate/events"
  homeassistant:
    enabled: true  # Home Assistant Discovery aktiviert
    discovery_prefix: "homeassistant"  # Standard-Präfix für Home Assistant
    publish_results: true  # Erkennungsergebnisse veröffentlichen

storage:
  path: "/data"
  snapshots_path: "/data/snapshots"
  processed_path: "/data/processed"
  training_path: "/data/training"

opencv:
  enabled: true
  use_gpu: false
  person_detection:
    method: "hog"  # Options: "hog", "dnn"
    confidence_threshold: 0.5
    scale_factor: 1.05
    min_neighbors: 2
    min_size_width: 64
    min_size_height: 128

# =========================================================================
# OPTIONAL: CompreFace-Integration für Gesichtserkennung
# Wenn du nur OpenCV für Personenerkennung nutzen möchtest und keine
# Gesichtserkennung benötigst, kannst du diesen Abschnitt auskommentieren
# oder 'enabled: false' setzen.
# =========================================================================
compreface:
  enabled: true  # Aktiviert für den Test
  subjects_api_url: "http://compreface:8000/api/v1/recognition/subjects"
  detection_api_url: "http://compreface:8000/api/v1/detection/detect"
  recognition_api_url: "http://compreface:8000/api/v1/recognition/recognize"
  verification_api_url: "http://compreface:8000/api/v1/verification/verify"
  api_key: "83c64961-b02c-4fe2-8fc1-bf39ac58c9f5"
  detection_threshold: 0.7
  recognition_threshold: 0.7
  limit: 0
  status_check_interval: 1
  status_check_timeout: 30

processor:
  image_processing_interval: 5
  max_workers: 5
  max_processing_time: 30
