services:
  # Double-Take-Go Server
  double-take:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Berlin
    networks:
      - double-take-network

networks:
  double-take-network:
    driver: bridge
