version: '3.8'

services:
  double-take:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Berlin
      - CONFIG_PATH=/config/config.yaml
    command: /bin/sh -c "echo 'Double-Take-Go wird aufgrund von Abhängigkeitsproblemen noch nicht automatisch gestartet.' && tail -f /dev/null"
