# Docker Compose Konfiguration für CPU-basierte Verarbeitung

services:
  # CPU Version (funktioniert auf allen Plattformen)
  double-take:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
      # Plattform explizit setzen für bessere Kompatibilität
      # amd64 = Standard Intel/AMD 64-bit Prozessoren
      args:
        - BUILDPLATFORM=linux/amd64
        - TARGETPLATFORM=linux/amd64
    container_name: double-take
    restart: always
    # Standard-Port für Double-Take UI
    ports:
      - "3000:3000"
    volumes:
      - ../../config:/config  # Konfigurationsdateien
      - ../../data:/data      # Persistente Daten direkt im Projektverzeichnis
    environment:
      - TZ=Europe/Berlin  # Zeitzone anpassen falls nötig
    platform: linux/amd64  # Explizite Plattformdefinition

  # InsightFace (optional, wenn Sie es statt CompreFace verwenden möchten)
  insightface:
    image: insightface/insightface-rest:v0.7.3
    container_name: insightface
    restart: always
    ports:
      - "18081:18081"
    volumes:
      - ../../data/insightface:/workspace/models
    environment:
      - TZ=Europe/Berlin
      - PYTHONUNBUFFERED=0
      - INFERENCE_BACKEND=ort  # Optimierter CPU-Modus mit ONNX Runtime
    platform: linux/amd64
    # Beim ersten Start werden Modelle heruntergeladen, was einige Zeit dauern kann
    # Bitte haben Sie Geduld, bis der Container vollständig gestartet ist

  # HINWEIS: CompreFace und MQTT werden als externe Dienste verwendet
  # und sind nicht Teil dieser docker-compose Konfiguration.
  # Bitte stellen Sie sicher, dass diese Dienste auf ihren externen
  # Servern verfügbar sind und in config.yaml richtig konfiguriert sind.

# Keine benannten Docker-Volumes mehr erforderlich, da direkte Verzeichnis-Mappings verwendet werden
