version: '3.8'

services:
  # CPU Version (funktioniert auf allen Plattformen)
  double-take:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
      # Plattform explizit setzen für bessere Kompatibilität
      # amd64 = Standard Intel/AMD 64-bit Prozessoren
      args:
        - BUILDPLATFORM=linux/amd64
        - TARGETPLATFORM=linux/amd64
    container_name: double-take
    restart: always
    # Standard-Port für Double-Take UI
    ports:
      - "3000:3000"
    volumes:
      - ../../config:/config  # Konfigurationsdateien
      - double-take-data:/data  # Persistente Daten
    environment:
      - TZ=Europe/Berlin  # Zeitzone anpassen falls nötig
    platform: linux/amd64  # Explizite Plattformdefinition

  # HINWEIS: CompreFace und MQTT werden als externe Dienste verwendet
  # und sind nicht Teil dieser docker-compose Konfiguration.
  # Bitte stellen Sie sicher, dass diese Dienste auf ihren externen
  # Servern verfügbar sind und in config.yaml richtig konfiguriert sind.

volumes:
  # Nur das Double-Take-Volume wird benötigt
  double-take-data:
