version: '3.8'

services:
  # AMD GPU Version (benötigt ROCm Support)
  double-take:
    build:
      context: ../..
      dockerfile: docker/amd/Dockerfile
      # Plattform explizit setzen für bessere Kompatibilität
      # amd64 = Standard Intel/AMD 64-bit Prozessoren
      args:
        - BUILDPLATFORM=linux/amd64
        - TARGETPLATFORM=linux/amd64
    container_name: double-take
    restart: always
    # Standard-Port für Double-Take UI
    ports:
      - "3000:3000"
    volumes:
      - ../../config:/config  # Konfigurationsdateien
      - double-take-data:/data  # Persistente Daten
    environment:
      - TZ=Europe/Berlin  # Zeitzone anpassen falls nötig
    platform: linux/amd64  # Explizite Plattformdefinition
    # AMD GPU Zugriff konfigurieren
    devices:
      - /dev/kfd:/dev/kfd  # ROCm Kernel Fusion Driver
      - /dev/dri:/dev/dri  # Direct Rendering Manager
      
  # ========================================================================
  # OPTIONAL: CompreFace-Services für Gesichtserkennung
  # Entkommentiere diese Blöcke, wenn du die Gesichtserkennung nutzen möchtest
  # Hinweis: Die OpenCV-Integration funktioniert auch ohne CompreFace!
  # ========================================================================
  
  # compreface-postgres:
  #   image: postgres:13.4
  #   container_name: compreface-postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=frs
  #   volumes:
  #     - compreface-db:/var/lib/postgresql/data

  # compreface-api:
  #   image: exadel/compreface-api:latest
  #   container_name: compreface-api
  #   restart: always
  #   depends_on:
  #     - compreface-postgres
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://compreface-postgres:5432/frs
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  #     - SPRING_PROFILES_ACTIVE=dev
  #   volumes:
  #     - compreface-data:/root/.frs

  # compreface-ui:
  #   image: exadel/compreface-fe:latest
  #   container_name: compreface-ui
  #   restart: always
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - compreface-api
  
  # Wenn du CompreFace aktivierst, füge diese Abhängigkeit zum double-take Service hinzu:
  # depends_on:
  #   - compreface-api

volumes:
  # Aktiviere diese Volumes, wenn du CompreFace verwendest
  # compreface-db:
  # compreface-data:
  double-take-data:
