# Double-Take-Go-Reborn Configuration for NVIDIA GPU acceleration with OpenCV
# Diese Konfiguration ist optimiert für NVIDIA GPUs mit CUDA-Unterstützung
# HINWEIS: OpenCV kann unabhängig von CompreFace verwendet werden

log:
  level: "info"
  format: "text"
  timestamp: true

server:
  port: 3000
  host: "0.0.0.0"
  base_url: "http://localhost:3000"
  metrics_enabled: true

mqtt:
  enabled: true
  broker: "192.168.0.55"
  port: 1883
  username: "hans"
  password: "desert"
  client_id: "double-take-go"
  topic_prefix: "double-take"
  topic: "frigate/events"
  homeassistant:
    enabled: true  # Home Assistant Discovery aktiviert
    discovery_prefix: "homeassistant"  # Standard-Präfix für Home Assistant
    publish_results: true  # Erkennungsergebnisse veröffentlichen

storage:
  path: "/data"
  snapshots_path: "/data/snapshots"
  processed_path: "/data/processed"
  training_path: "/data/training"

opencv:
  enabled: true
  use_gpu: true
  backend: "cuda"  # Use CUDA backend for OpenCV DNN
  target: "cuda"   # Target compute device is CUDA
  person_detection:
    method: "dnn"  # DNN method is preferred for GPU acceleration
    confidence_threshold: 0.7
    scale_factor: 1.03
    min_neighbors: 3
    min_size_width: 64
    min_size_height: 128

compreface:
  enabled: true
  url: "http://10.100.0.3:8100"
  subjects_api_url: "http://10.100.0.3:8100/api/v1/recognition/subjects"
  detection_api_url: "http://10.100.0.3:8100/api/v1/detection/detect"
  recognition_api_url: "http://10.100.0.3:8100/api/v1/recognition/recognize"
  verification_api_url: "http://10.100.0.3:8100/api/v1/verification/verify"
  recognition_api_key: "83c64961-b02c-4fe2-8fc1-bf39ac58c9f5"
  detection_api_key: "83c64961-b02c-4fe2-8fc1-bf39ac58c9f5"
  detection_threshold: 0.7
  recognition_threshold: 0.7
  limit: 0
  status_check_interval: 1
  status_check_timeout: 30

frigate:
  enabled: true
  event_topic: "frigate/events"
  process_person_only: true
  url: "http://192.168.0.55:5000/"
  host: "http://192.168.0.55:5000/"

processor:
  image_processing_interval: 5
  max_workers: 5
  max_processing_time: 30
  face_recognition_provider: "compreface"

insightface:
  enabled: true
  url: "http://insightface:18081"
  detect_url: "http://insightface:18081/extract"
  recognize_url: "http://insightface:18081/recognize"
  add_face_url: "http://insightface:18081/add_face"
  detection_threshold: 0.6
  recognition_threshold: 0.5
  max_faces: 10
  status_check_interval: 1
  status_check_timeout: 30
