# Double-Take-Go Configuration Example

server:
  host: "0.0.0.0"
  port: 3000
  snapshot_dir: "/data/snapshots"
  snapshot_url: "/snapshots"
  template_dir: "/app/web/templates"
  timezone: "Europe/Berlin"

log:
  level: "debug"
  file: "/data/logs/double-take.log"

db:
  # SQLite configuration
  file: "/data/double-take.db"
  # PostgreSQL configuration (uncomment if needed)
  # username: "postgres"
  # password: "password"
  # host: "localhost"
  # port: 5432
  # name: "double_take"

compreface:
  enabled: true
  url: "http://10.100.0.3:8000"
  recognition_api_key: "83c64961-b02c-4fe2-8fc1-bf39ac58c9f5"
  detection_api_key: "your_detection_api_key"
  det_prob_threshold: 0.8
  sync_interval_minutes: 15

mqtt:
  enabled: true
  broker: "192.168.0.55"
  port: 1883
  username: "hans"
  password: "desert"
  client_id: "double-take-go"
  topic: "frigate/#"

frigate:
  enabled: true
  api_url: "http://192.168.0.55:5000"
  url: "http://192.168.0.55:5000"

cleanup:
  retention_days: 30