# Double-Take-Go-Reborn Configuration for AMD GPU acceleration with OpenCV
# Diese Konfiguration ist optimiert für AMD GPUs mit OpenCL-Unterstützung
# HINWEIS: OpenCV kann unabhängig von CompreFace verwendet werden

log:
  level: "info"
  format: "text"
  timestamp: true

server:
  port: 3000
  host: "0.0.0.0"
  base_url: "http://localhost:3000"
  metrics_enabled: true

mqtt:
  enabled: false
  broker: "tcp://localhost:1883"
  username: ""
  password: ""
  client_id: "double-take-go"
  topic_prefix: "double-take"

storage:
  path: "/data"
  snapshots_path: "/data/snapshots"
  processed_path: "/data/processed"
  training_path: "/data/training"

opencv:
  enabled: true
  use_gpu: true
  person_detection:
    method: "dnn"  # DNN method is preferred for GPU acceleration
    confidence_threshold: 0.6
    scale_factor: 1.03
    min_neighbors: 3
    min_size_width: 64
    min_size_height: 128
    # GPU-specific DNN parameters
    backend: "opencl"  # Use OpenCL backend for OpenCV DNN
    target: "opencl"   # Target compute device is OpenCL

# =========================================================================
# OPTIONAL: CompreFace-Integration für Gesichtserkennung
# Wenn du nur OpenCV für Personenerkennung nutzen möchtest und keine
# Gesichtserkennung benötigst, kannst du diesen Abschnitt auskommentieren
# oder 'enabled: false' setzen.
# =========================================================================
compreface:
  enabled: false  # Auf 'true' setzen, wenn CompreFace verwendet werden soll
  subjects_api_url: "http://compreface:8000/api/v1/recognition/subjects"
  detection_api_url: "http://compreface:8000/api/v1/detection/detect"
  recognition_api_url: "http://compreface:8000/api/v1/recognition/recognize"
  verification_api_url: "http://compreface:8000/api/v1/verification/verify"
  api_key: "83c64961-b02c-4fe2-8fc1-bf39ac58c9f5"
  detection_threshold: 0.7
  recognition_threshold: 0.7
  limit: 0
  status_check_interval: 1
  status_check_timeout: 30

processor:
  image_processing_interval: 5
  max_workers: 10  # Increased worker count for GPU hardware
  max_processing_time: 30
